/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

/**
 *
 * @author gatub
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void jButtonSalidaActionPerformed (java.awt.event.ActionEvent evt) {
        System.exit(0);
    } 

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelFondoA = new javax.swing.JLabel();
        ComboContinente = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabelFondoB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabel1.setText("RINCONES DULCES DE EUROPA Y ASIA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 1070, 160));

        jLabelFondoA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoA.jpg"))); // NOI18N
        getContentPane().add(jLabelFondoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 250));

        ComboContinente.setEditable(true);
        ComboContinente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ComboContinente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Continente>", "Asia", "Europa" }));
        ComboContinente.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ComboContinenteAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ComboContinente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboContinenteActionPerformed(evt);
            }
        });
        getContentPane().add(ComboContinente, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 370, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Por favor seleccione un continente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabelFondoB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pink.jpg"))); // NOI18N
        getContentPane().add(jLabelFondoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 252, -1, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboContinenteAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ComboContinenteAncestorAdded
      
    }//GEN-LAST:event_ComboContinenteAncestorAdded

    private void ComboContinenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboContinenteActionPerformed
        String seleccion = (String) ComboContinente.getSelectedItem();

    if ("Asia".equals(seleccion)) {
        new AsiaPanel().setVisible(true); // Abre la ventana AsiaPanel
        this.dispose(); // Cierra la ventana principal (Interfaz)
    } else if ("Europa".equals(seleccion)) {
        new EuropaPanel().setVisible(true); // Abre la ventana EuropaPanel
        this.dispose(); // Cierra la ventana principal (Interfaz)
    }
    }//GEN-LAST:event_ComboContinenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboContinente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFondoA;
    private javax.swing.JLabel jLabelFondoB;
    // End of variables declaration//GEN-END:variables
}
